### ISSUE TITLE
I use my trained onnx model, but it can't work.

### ISSUE THREAD

**Issue by Wei0703** [stunback/ros-nanodet#1]
Hi,
I follow [NanoDet github](https://github.com/RangiLyu/nanodet) train my own model.
But it look like no bounding boxes in mlvl_bboxes array.
How can I solved it?

![nanodet_ros_error](https://user-images.githubusercontent.com/59257988/159912214-bd6edc1a-5404-48ae-b2b6-bfc3d82af463.png)

And following text is my training config
```
# nanodet-EfficientNet-Lite1_416
save_dir: workspace/RepVGG-A0-416
model:
  arch:
    name: OneStageDetector
    backbone:
      name: RepVGG
      arch: A0
      out_stages: [2,3,4]
      activation: ReLU
      last_channel: 512
      deploy: False
    fpn:
      name: PAN
      in_channels: [96, 192, 512]
      out_channels: 128
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      conv_type: Conv
      input_channel: 128
      feat_channels: 128
      stacked_convs: 2
      activation: ReLU
      share_cls_reg: True
      octave_base_scale: 8
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 10
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: CocoDataset
    img_path: /nfs/Workspace/dataset/mscoco/images/train2017
    ann_path: /nfs/Workspace/dataset/mscoco/annotations/annotations/instances_train2017_person.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.5, 1.5]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: CocoDataset
    img_path: /nfs/Workspace/dataset/mscoco/images/val2017
    ann_path: /nfs/Workspace/dataset/mscoco/annotations/annotations/instances_val2017_person.json
    input_size: [416,416] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 1
  batchsize_per_gpu: 100
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.07
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 500
    ratio: 0.01
  total_epochs: 170
  lr_schedule:
    name: MultiStepLR
    milestones: [130,150,160,165]
    gamma: 0.1
  val_intervals: 5
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['person']
```
Thank a lot!
